---
- name: "Ubuntu setup"
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  vars_files:
    - vars/default.yml
    
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: ["aptitude"]

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Install fonts-firacode and vim
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['fonts-firacode', 'vim', 'filezilla']

    - import_tasks: snap_tasks.yml
    
    - name: Run whoami without become.
      command: whoami
      changed_when: false
      become: false
      register: whoami

    - name: Set a fact with the user name.
      set_fact:
        login_user: "{{ whoami.stdout }}"

    - import_tasks: zoom_tasks.yml 
      vars:
        login_user: "{{ login_user }}"

    - import_role:
        name: darkwizard242.terraform
    - import_role:
        name: darkwizard242.packer
    - import_role:
        name: darkwizard242.azurecli
    - import_role:
        name: darkwizard242.vagrant
    - import_role:
        name: darkwizard242.kubens
    - import_role:
        name: pandemonium1986.kubectl
