roles:
  - src: grzegorznowak.nvm_node
    name: grzegorznowak.nvm_node
  - baztian.jetbrains_toolbox
  - darkwizard242.terraform
  - darkwizard242.packer
  - darkwizard242.vagrant
  - darkwizard242.azurecli
  - darkwizard242.kubens
  - pandemonium1986.kubectl
  - deluxebrain.ansible_role_docker
  - gantsign.oh-my-zsh
  # - pandemonium1986.kubectx

# collections:
#   - azure.azcollection
  # - name: community.docker
