roles:
  - baztian.jetbrains_toolbox
  - darkwizard242.terraform
  - darkwizard242.packer
  - darkwizard242.vagrant
  - darkwizard242.azurecli
  - darkwizard242.kubens
  - pandemonium1986.kubectl
  - deluxebrain.ansible_role_docker
  - gantsign.oh-my-zsh
  - grzegorznowak.nvm_node
  # - pandemonium1986.kubectx
  # - src: grzegorznowak.nvm_node
    # name: grzegorznowak.nvm_node
  

# collections:
#   - azure.azcollection
  # - name: community.docker
