# deluxebrain.ansible_role_docker
docker_users:
  - roger

oh_my_zsh_theme: af-magic
oh_my_zsh_plugins:
  - git
  - terraform 
  - docker 
  - kubectl 
  - kubectx
users:
  - username: roger
    
nvm_node_version: "16.9.1"
nvm_user_name: "roger"
nvm_install_globally:
  - yarn
  - typescript
  - serverless